apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion
  template:
    metadata:
      labels:
        app: motion
    spec:
      containers:
        - name: motion
          image: motion
          args:
            - --experimentalSingularityStore
            - --experimentalRemoteSingularityAPIUrl=http://singularity:9090
          envFrom:
            - configMapRef:
                name: motion-env
          ports:
            - containerPort: 40080
              name: api