name: Boost Devnet
description: Start up Boost Devnet
inputs:
  name:
    required: true
    type: string
  target:
    required: false
    type: string
  file:
    required: false
    type: string
  context:
    required: false
    type: string
    default: '.'
  build-args:
    required: false
    type: string
  push:
    required: false
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    - name: Run Devnet
      shell: bash
      working-directory: /tmp
      run: |
        git clone --depth 1 --branch masih/gh-actions https://github.com/filecoin-shipyard/rockbed.git
        cd rockbed
        git pull
        cd deploy/docker-compose/devnet
        docker compose up -d
