apiVersion: apps/v1
kind: Deployment
metadata:
  name: singularity
spec:
  selector:
    matchLabels:
      app: singularity
  template:
    metadata:
      labels:
        app: singularity
    spec:
      containers:
        - name: api
          image: singularity
          args:
            - run
            - api
            - --bind
            - :9090
          envFrom:
            - secretRef:
                name: singularity-db-creds
          env:
            - name: DATABASE_CONNECTION_STRING
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
          ports:
            - containerPort: 9090
              name: api
        - name: dataset-worker
          image: singularity
          args:
            - run
            - dataset-worker
          envFrom:
            - secretRef:
                name: singularity-db-creds
          env:
            - name: DATABASE_CONNECTION_STRING
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        - name: deal-pusher
          image: singularity
          args:
            - run
            - deal-pusher
          envFrom:
            - secretRef:
                name: singularity-db-creds
          env:
            - name: DATABASE_CONNECTION_STRING
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        - name: deal-tracker
          image: singularity
          args:
            - run
            - deal-tracker
          envFrom:
            - secretRef:
                name: singularity-db-creds
          env:
            - name: DATABASE_CONNECTION_STRING
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
---
apiVersion: v1
kind: Service
metadata:
  name: singularity
spec:
  selector:
    app: singularity
  ports:
    - port: 9090
      targetPort: api
