name: Test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: filecoin-shipyard/rockbed/.github/actions/setup-rockbed@masih/gh-actions
      - name: Test checked out
        run: |
          ls -alh "${{ runner.temp }}"
          ls -alh "/tmp"